<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.8.1 on win32)" generated="20231102 15:01:46.787" rpa="false" schemaversion="4">
<suite id="s1" name="Home" source="c:\automationTests\twp\tests\home.robot">
<test id="s1-t1" name="open Application with Appium" line="8">
<status status="FAIL" starttime="20231102 15:01:46.842" endtime="20231102 15:01:46.843">Test cannot be empty.</status>
</test>
<status status="FAIL" starttime="20231102 15:01:46.802" endtime="20231102 15:01:46.844"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Home">Home</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231102 15:01:46.831" level="ERROR">Error in file 'c:\automationTests\twp\tests\home.robot' on line 3: Error in file 'c:\automationTests\twp\resources\basic.robot' on line 6: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
